language: objective-c
xcode_workspace: AeroGearSyncClientJsonPatch.xcworkspace
xcode_scheme: AeroGearSyncClientJsonPatch
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master

matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8
script:
  - xcodebuild -workspace AeroGearSyncClientJsonPatch.xcworkspace -scheme AeroGearSyncClientJsonPatch -sdk iphonesimulator build