language: objective-c
osx_image: xcode7.3
xcode_workspace: AeroGearSyncClientJsonPatch.xcworkspace
xcode_scheme: AeroGearSyncClientJsonPatch
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
